// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh9hpOPDZZX24jY5rWDsZkI86UBfUX8yA',
    appId: '1:885584363406:web:6896cfca44086efa4beedf',
    messagingSenderId: '885584363406',
    projectId: 'smarthome-f314e',
    authDomain: 'smarthome-f314e.firebaseapp.com',
    databaseURL: 'https://smarthome-f314e-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-f314e.appspot.com',
    measurementId: 'G-F5XTSZZ2VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9YXxrDRoaW3HxfsyzYIp5YtOfUnDFFGo',
    appId: '1:885584363406:android:00f2dd6f9a97316d4beedf',
    messagingSenderId: '885584363406',
    projectId: 'smarthome-f314e',
    databaseURL: 'https://smarthome-f314e-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-f314e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDfJdpkYnUPhc3hHV4vWIiP1VeAn-ZuhE',
    appId: '1:885584363406:ios:38354e9ebf200e894beedf',
    messagingSenderId: '885584363406',
    projectId: 'smarthome-f314e',
    databaseURL: 'https://smarthome-f314e-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-f314e.appspot.com',
    iosBundleId: 'com.example.myp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDfJdpkYnUPhc3hHV4vWIiP1VeAn-ZuhE',
    appId: '1:885584363406:ios:38354e9ebf200e894beedf',
    messagingSenderId: '885584363406',
    projectId: 'smarthome-f314e',
    databaseURL: 'https://smarthome-f314e-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-f314e.appspot.com',
    iosBundleId: 'com.example.myp',
  );
}
